### ISSUE TITLE
Dagobah/Pymongo not handling non-UTF-8 chars well

### ISSUE THREAD

**Issue by gsksivesh** [gsksivesh/dagobah#37]
<a href="https://github.com/rclough"><img src="https://avatars1.githubusercontent.com/u/186589?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rclough](https://github.com/rclough)**
_Tuesday Dec 02, 2014 at 22:04 GMT_
_Originally opened as https://github.com/thieman/dagobah/issues/133_

----

Categorize under "more things that can break in task/job completion backend code"

Unfortunately due to the semi-sensitive content of the log in question, I have to clean the string that broke it, but here is the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/dagobah/core/core.py", line 828, in check_complete
    complete_time=datetime.utcnow())
  File "/usr/local/lib/python2.7/site-packages/dagobah/core/core.py", line 1031, in _task_complete
    self.parent_job._complete_task(self.name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/dagobah/core/core.py", line 531, in _complete_task
    self._commit_run_log()
  File "/usr/local/lib/python2.7/site-packages/dagobah/core/core.py", line 626, in _commit_run_log
    self.backend.commit_log(self.run_log)
  File "/usr/local/lib/python2.7/site-packages/dagobah/backend/mongo.py", line 133, in commit_log
    self.log_coll.save(dict(log_json.items() + append.items()))
  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 288, in save
    manipulate, safe, check_keys=check_keys, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 551, in update
    docs, check_keys, self.uuid_subtype, client)
InvalidStringData: strings in documents must be valid UTF-8: "<REDACTED>"
```

**Comment by gsksivesh** [comment]
<a href="https://github.com/rclough"><img src="https://avatars1.githubusercontent.com/u/186589?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rclough](https://github.com/rclough)**
_Tuesday Dec 02, 2014 at 22:07 GMT_

----

Consensus on the interweb (FWIW) seems to be that we need to somehow enforce UTF-8 strings before passing them to pymongo.

**Comment by gsksivesh** [comment]
<a href="https://github.com/rclough"><img src="https://avatars1.githubusercontent.com/u/186589?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rclough](https://github.com/rclough)**
_Tuesday Dec 02, 2014 at 22:17 GMT_

----

Something like this maybe: http://stackoverflow.com/a/19230566/124537

**Comment by gsksivesh** [comment]
<a href="https://github.com/thieman"><img src="https://avatars1.githubusercontent.com/u/1414305?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thieman](https://github.com/thieman)**
_Tuesday Dec 02, 2014 at 22:50 GMT_

----

Oh, the joys of string encoding in Python 2. Will think on the best way to fix this.

**Comment by gsksivesh** [comment]
<a href="https://github.com/thieman"><img src="https://avatars1.githubusercontent.com/u/1414305?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thieman](https://github.com/thieman)**
_Wednesday Dec 03, 2014 at 01:50 GMT_

----

I'm in favor of forcing UTF-8 for Mongo string storage. I think this should be an implementation detail of the Mongo backend and should be implemented in that module. I'm conceptually fine with dropping any characters that can't be encoded as UTF-8.

I think it is important to limit this restriction as much as possible. If someone has an absolute requirement that their logs be stored as UTF-16 or something, they should be able to implement a backend that will support that.

**Comment by gsksivesh** [comment]
<a href="https://github.com/rclough"><img src="https://avatars1.githubusercontent.com/u/186589?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rclough](https://github.com/rclough)**
_Thursday Dec 04, 2014 at 15:56 GMT_

----

So you're saying (and I think I agree) that the force utf-8 code should be within the mongo.py backend, that way its specific to the backend code?

**Comment by gsksivesh** [comment]
<a href="https://github.com/thieman"><img src="https://avatars1.githubusercontent.com/u/1414305?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thieman](https://github.com/thieman)**
_Thursday Dec 04, 2014 at 15:59 GMT_

----

![](http://i.imgur.com/rJC4tYP.gif)
